#!/bin/bash

ENVIRON_FILE="/path-to-webserver/CGI/environ"
. $ENVIRON_FILE

while IFS== read -r name value
do 
   export ${name}
done < $ENVIRON_FILE

/path-to-webserver/CGI/search.py /path-to-webserver/Config/search.cfg
