#!/bin/bash

ENVIRON_FILE="path-to/Webserver/CGI/environ"
. $ENVIRON_FILE

while IFS== read -r name value
do 
   export ${name}
done < $ENVIRON_FILE

path-to/Webserver/CGI/go/facetSearch path-to/Webserver/Config/facet_searchGo.cfg 
